APP_NAME?=omat

GOOS?=darwin
GOARCH?=arm64

.DEFAULT_GOAL := help
.PHONY: help

setup_ci: ## Install/update tools needed at CI-time.
	if [ $$(wc -l < tools.ci) -gt 0 ]; then \
		cat tools.ci | while read TOOL; do \
			echo "Installing $${TOOL}..."; \
			go install $${TOOL}; \
		done; \
	fi

setup_workstation: setup_ci ## Install/update tools needed at dev-time.
	if [ $$(wc -l < tools.dev) -gt 0 ]; then \
		cat tools.dev | while read TOOL; do \
			echo "Installing $${TOOL}..."; \
			go install $${TOOL}; \
		done; \
	fi

setup: setup_ci setup_workstation ## Install/update all tools.

clean: ## Clean up.
	go clean

generate:  ## Generate any code, as needed.
	echo "$(shell cat .version) (SHA $(shell git rev-parse --short HEAD), $(shell date -u +%Y-%m-%dT%H:%M:%S%z))" > cmd/.version_string
	GOOS=${GOOS} GOARCH=${GOARCH} go generate ./...

test: generate ## Run test suite.
	go test -race -coverprofile coverage.txt ./...

compile: generate ## Compile code.
	GOOS=${GOOS} GOARCH=${GOARCH} go build -o "${APP_NAME}" main.go

build: test generate compile ## Run tests, generate code, compile code.

fmt: ## Tidy code.
	gofumpt -l -e -w $$(find . -name '*.go' | xargs grep -L 'Code generated by' | cut -d: -f1)

lint: clean ## Run Go linters, without auto-fixing.
	GOOS=${GOOS} GOARCH=${GOARCH} go vet ./...
	if [ $$(wc -l < tools.ci) -gt 0 ]; then \
		grep golang.org/x/tools/go/analysis/passes tools.ci | cut -d/ -f7 | while read TOOL; do \
			GOOS=${GOOS} GOARCH=${GOARCH} go vet -vettool=$$(which $$TOOL) ./...; \
		done \
	fi
	GOOS=${GOOS} GOARCH=${GOARCH} golangci-lint run

fix: ## Run transforms to simplify/correct known undesirable patterns of code.
	golangci-lint run --fix

cloc: ## Run cloc.
	cloc .
	@echo

help:
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "%-20s %s\n", $$1, $$2}'
